version: '3.4'

services:

#   user:
#     container_name: users
#     build:
#       context: ~/cfpb_dev/dev_PythonMicroservices/proj_docker-flask-react/testdriven-app/services/users
#       dockerfile: Dockerfile-dev
# #   command:
# #     - './testentry.sh'
#     volumes:
#       - '~/cfpb_dev/dev_PythonMicroservices/proj_docker-flask-react/testdriven-app/services/users:/usr/src/app'
#     ports:
#       - 5001:5000
#     environment:
#       - FLASK_APP=project/__init__.py
#       - FLASK_DEBUG=1
#       - APP_SETTINGS=project.config.DevelopmentConfig
# #     - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
#       - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
# #     - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
#       - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
#     depends_on:
#       - users-db
#     links:
#       - users-db
  postgresql-10:
    container_name: postgresql-10 
    build:
      context: ./postgres10.x 
      dockerfile: Dockerfile
#   command:
#     - './docker-entrypoint.sh'
    ports:
      - 5410:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
